from typing import Any, Dict, Callable

class BaseTemplate:
    template_text: str
    kwargs: Dict[str, Any]
    _template: Any
    def __init__(self, template_text: str, **kwargs: Any) -> None: ...
    def set_template_text(self, template_text: str) -> None: ...
    def render(self, **kwargs: Any) -> str: ...
    def compile_template(self) -> Any: ...
    @property
    def template(self) -> Any: ...

class StringTemplate(BaseTemplate):
    def compile_template(self) -> Callable[..., str]: ...
    def render(self, **kwargs: Any) -> str: ...
