[tox]
envlist = py310, py311, py312, py313, py314, pypy, style

[testenv]
passenv = TEST_*,SMTP_TEST_*
commands = py.test --cov-report term --cov-report html --cov emails {posargs}

[testenv:pypy]
deps =
    -rrequirements/tests.txt

[testenv:py310]
deps =
    -rrequirements/tests.txt

[testenv:py311]
deps =
    -rrequirements/tests.txt

[testenv:py312]
deps =
    -rrequirements/tests.txt

[testenv:py313]
deps =
    -rrequirements/tests.txt

[testenv:py314]
deps =
    -rrequirements/tests.txt


[testenv:django42]
basepython = python3.12
deps =
    -rrequirements/tests-django.txt
    Django>=4.2,<4.3
commands = py.test --cov-report term --cov-report html --cov emails -m django {posargs}

[testenv:django52]
basepython = python3.12
deps =
    -rrequirements/tests-django.txt
    Django>=5.2,<5.3
commands = py.test --cov-report term --cov-report html --cov emails -m django {posargs}

[testenv:django60]
basepython = python3.12
deps =
    -rrequirements/tests-django.txt
    Django>=6.0,<6.1
commands = py.test --cov-report term --cov-report html --cov emails -m django {posargs}

[testenv:typecheck]
deps = mypy
commands = mypy emails/

[testenv:style]
deps = pre-commit
skip_install = true
commands = pre-commit run --all-files --show-diff-on-failure