from typing import Any, Optional, Dict, Type, List
from .local_store import FileSystemLoader as FileSystemLoader, ZipLoader as ZipLoader, MsgLoader as MsgLoader, FileNotFound as FileNotFound
from .helpers import guess_charset as guess_charset

class LoadError(Exception): ...
class IndexFileNotFound(LoadError): ...
class InvalidHtmlFile(LoadError): ...

def from_html(html: str, text: Optional[str] = ..., base_url: Optional[str] = ..., message_params: Optional[Dict[str, Any]] = ..., local_loader: Optional[Any] = ..., template_cls: Optional[Type[Any]] = ..., message_cls: Optional[Type[Any]] = ..., source_filename: Optional[str] = ..., requests_params: Optional[Dict[str, Any]] = ..., **kwargs: Any) -> Any: ...
