from typing import Any, Optional, List, Tuple, Union, Iterator
# from .helpers import decode_text

class FileNotFound(Exception): ...

def split_template_path(template: str) -> List[str]: ...
def open_if_exists(filename: str, mode: str = ...) -> Optional[Any]: ...

class BaseLoader:
    def __getitem__(self, filename: str) -> Optional[bytes]: ...
    def get_file(self, name: str) -> Tuple[Optional[bytes], Optional[float]]: ...
    def list_files(self) -> Iterator[str]: ...
    def content(self, filename: str, is_html: bool = ..., decode: bool = ..., guess_charset: bool = ..., charset: str = ...) -> Union[str, bytes, None]: ...
    def find_index_file(self, filename: Optional[str] = ..., extensions: Tuple[str, ...] = ..., stop_names: Tuple[str, ...] = ..., raise_if_not_found: bool = ...) -> Optional[str]: ...

class FileSystemLoader(BaseLoader):
    searchpath: List[str]
    encoding: str
    base_path: Optional[str]
    def __init__(self, searchpath: Union[str, List[str]], encoding: str = ..., base_path: Optional[str] = ...) -> None: ...
    def get_file(self, name: str) -> Tuple[Optional[bytes], Optional[float]]: ...
    def list_files(self) -> Iterator[str]: ...

class ZipLoader(BaseLoader):
    zipfile: Any
    encoding: str
    base_path: Optional[str]
    _decoded_filenames: Optional[Any]
    _original_filenames: Optional[Any]
    def __init__(self, file: Any, encoding: str = ..., base_path: Optional[str] = ...) -> None: ...
    def get_file(self, name: str) -> Tuple[Optional[bytes], Optional[float]]: ...
    def list_files(self) -> Iterator[str]: ...

class MsgLoader(BaseLoader):
    msg: Any
    base_path: Optional[str]
    _html_parts: List[Any]
    _text_parts: List[Any]
    _files: Any
    _content_ids: Any
    _parsed: bool
    headers: Any
    def __init__(self, msg: Any, base_path: Optional[str] = ...) -> None: ...
    def get_file(self, name: str) -> Tuple[Optional[bytes], Optional[float]]: ...
    def list_files(self) -> Iterator[str]: ...
    @property
    def attachments(self) -> Any: ...
    @property
    def html(self) -> Any: ...
    @property
    def text(self) -> Any: ...
