from typing import Any, Optional, Tuple, List, Union

class DKIMException(Exception): ...
class UnparsableKeyError(DKIMException): ...

def sign(message: Union[str, bytes], selector: bytes, domain: bytes, privkey: bytes, identity: Optional[bytes] = ..., canonicalize: Tuple[bytes, bytes] = ..., signature_algorithm: bytes = ..., include_headers: Optional[List[str]] = ..., length: bool = ..., logger: Optional[Any] = ...) -> bytes: ...
