from typing import Any, Dict, Type, TypeVar

T = TypeVar('T')

def simple_dict2str(d: Dict[str, Any]) -> str: ...

class ObjectFactory:
    cls: Type[Any]
    pool: Dict[str, Any]
    def __init__(self, cls: Type[Any]) -> None: ...
    def __getitem__(self, k: Dict[str, Any]) -> Any: ...
    def invalidate(self, k: Dict[str, Any]) -> Any: ...
