from typing import Any, Optional, Union, Tuple, List, Dict, Callable, Set, Type
from .store import BaseFile, MemoryFileStore
from .signers import DKIMSigner
from .backend import ObjectFactory, SMTPBackend
from .transformer import MessageTransformer

class BaseMessage:
    attachment_cls: Type[BaseFile]
    filestore_cls: Type[MemoryFileStore]
    policy: Any
    _attachments: Optional[MemoryFileStore]
    charset: str
    headers_encoding: str
    _message_id: Union[str, Callable[[], str], None]
    render_data: Dict[str, Any]
    _mail_from: Optional[Tuple[str, str]]
    _mail_to: List[Tuple[str, str]]
    _cc: List[Tuple[str, str]]
    _bcc: List[Tuple[str, str]]
    _headers: Dict[str, Any]
    _html: Any
    _html_url: Optional[str]
    _text: Any
    _text_url: Optional[str]
    _subject: Optional[str]
    _date: Union[str, Callable[[], str], bool, None]

    def __init__(self,
                 charset: str = ...,
                 message_id: Union[str, Callable[[], str], None] = ...,
                 date: Union[str, Callable[[], str], bool, None] = ...,
                 subject: Optional[str] = ...,
                 mail_from: Union[str, Tuple[str, str], None] = ...,
                 mail_to: Union[str, List[str], Tuple[str, str], List[Tuple[str, str]], None] = ...,
                 headers: Optional[Dict[str, Any]] = ...,
                 html: Any = ...,
                 text: Any = ...,
                 attachments: Optional[List[Any]] = ...,
                 cc: Union[str, List[str], Tuple[str, str], List[Tuple[str, str]], None] = ...,
                 bcc: Union[str, List[str], Tuple[str, str], List[Tuple[str, str]], None] = ...,
                 headers_encoding: Optional[str] = ...) -> None: ...
    
    def set_mail_from(self, mail_from: Union[str, Tuple[str, str], None]) -> None: ...
    def get_mail_from(self) -> Optional[Tuple[str, str]]: ...
    mail_from: Optional[Tuple[str, str]]

    def set_mail_to(self, mail_to: Union[str, List[str], Tuple[str, str], List[Tuple[str, str]], None]) -> None: ...
    def get_mail_to(self) -> List[Tuple[str, str]]: ...
    mail_to: List[Tuple[str, str]]

    def set_cc(self, addr: Union[str, List[str], Tuple[str, str], List[Tuple[str, str]], None]) -> None: ...
    def get_cc(self) -> List[Tuple[str, str]]: ...
    cc: List[Tuple[str, str]]

    def set_bcc(self, addr: Union[str, List[str], Tuple[str, str], List[Tuple[str, str]], None]) -> None: ...
    def get_bcc(self) -> List[Tuple[str, str]]: ...
    bcc: List[Tuple[str, str]]

    def get_recipients_emails(self) -> List[str]: ...
    def set_headers(self, headers: Optional[Dict[str, Any]]) -> None: ...
    
    def set_html(self, html: Any, url: Optional[str] = ...) -> None: ...
    def get_html(self) -> Any: ...
    html: Any

    def set_text(self, text: Any, url: Optional[str] = ...) -> None: ...
    def get_text(self) -> Any: ...
    text: Any

    @property
    def html_body(self) -> Any: ...
    @property
    def text_body(self) -> Any: ...

    def set_subject(self, value: Optional[str]) -> None: ...
    def get_subject(self) -> Optional[str]: ...
    subject: Optional[str]

    def render(self, **kwargs: Any) -> None: ...

    def set_date(self, value: Union[str, Callable[[], str], bool, None]) -> None: ...
    def get_date(self) -> Optional[str]: ...
    date: Optional[str]
    message_date: Optional[str]

    @property
    def message_id(self) -> Optional[str]: ...
    @message_id.setter
    def message_id(self, value: Union[str, Callable[[], str], None]) -> None: ...

    @property
    def attachments(self) -> MemoryFileStore: ...
    def attach(self, **kwargs: Any) -> None: ...

class MessageBuildMixin:
    ROOT_PREAMBLE: str
    ADDRESS_HEADERS: Set[str]
    before_build: Optional[Callable[[Any], None]]
    after_build: Optional[Callable[[Any, Any], None]]

    def encode_header(self, value: Any) -> Any: ...
    def encode_address_header(self, pair: Optional[Tuple[str, str]]) -> Optional[str]: ...
    encode_name_header: Callable[[Optional[Tuple[str, str]]], Optional[str]]
    def set_header(self, msg: Any, key: str, value: Any, encode: bool = ...) -> None: ...
    def _build_root_message(self, message_cls: Optional[Type[Any]] = ..., **kw: Any) -> Any: ...
    def _build_html_part(self) -> Any: ...
    def _build_text_part(self) -> Any: ...
    def build_message(self, message_cls: Optional[Type[Any]] = ...) -> Any: ...
    _build_message: Callable[[Optional[Type[Any]]], Any]
    def as_message(self, message_cls: Optional[Type[Any]] = ...) -> Any: ...
    message: Callable[[Optional[Type[Any]]], Any]
    def as_string(self, message_cls: Optional[Type[Any]] = ...) -> str: ...
    def as_bytes(self, message_cls: Optional[Type[Any]] = ...) -> bytes: ...

class MessageSendMixin:
    smtp_pool_factory: Type[ObjectFactory]
    smtp_cls: Type[SMTPBackend]
    @property
    def smtp_pool(self) -> ObjectFactory: ...
    def send(self,
             to: Union[str, List[str], Tuple[str, str], List[Tuple[str, str]], None] = ...,
             set_mail_to: bool = ...,
             mail_from: Union[str, Tuple[str, str], None] = ...,
             set_mail_from: bool = ...,
             render: Optional[Dict[str, Any]] = ...,
             smtp_mail_options: Optional[Any] = ...,
             smtp_rcpt_options: Optional[Any] = ...,
             smtp: Union[Dict[str, Any], Any, None] = ...) -> Any: ...

class MessageTransformerMixin:
    transformer_cls: Optional[Type[MessageTransformer]]
    _transformer: Optional[MessageTransformer]
    def create_transformer(self, transformer_cls: Optional[Type[MessageTransformer]] = ..., **kw: Any) -> MessageTransformer: ...
    def destroy_transformer(self) -> None: ...
    @property
    def transformer(self) -> MessageTransformer: ...
    def transform(self, **kwargs: Any) -> None: ...

class MessageSignMixin:
    signer_cls: Type[DKIMSigner]
    _signer: Optional[DKIMSigner]
    def sign(self, **kwargs: Any) -> Any: ...
    dkim: Callable[..., Any]
    def sign_message(self, msg: Any) -> Any: ...
    def sign_string(self, message_string: str) -> str: ...
    def sign_bytes(self, message_bytes: bytes) -> bytes: ...

class Message(MessageSendMixin, MessageTransformerMixin, MessageSignMixin, MessageBuildMixin, BaseMessage): ...

def html(**kwargs: Any) -> Message: ...

class DjangoMessageProxy:
    _message: Message
    _recipients: Optional[List[str]]
    _context: Dict[str, Any]
    from_email: str
    encoding: str
    def __init__(self, message: Message, recipients: Optional[List[str]] = ..., context: Optional[Dict[str, Any]] = ...) -> None: ...
    def recipients(self) -> List[str]: ...
    def message(self) -> Any: ...
