from typing import Any, Optional, Union, Tuple, Dict
from email.message import Message

class DKIMSigner:
    ignore_sign_errors: bool
    _sign_params: Dict[str, Any]

    def __init__(self, selector: str, domain: str, key: Union[str, bytes, Any] = ..., ignore_sign_errors: bool = ..., **kwargs: Any) -> None: ...
    def get_sign_string(self, message: Union[str, bytes]) -> Optional[bytes]: ...
    def get_sign_bytes(self, message: Union[str, bytes]) -> Optional[bytes]: ...
    def get_sign_header(self, message: Union[str, bytes]) -> Optional[Tuple[str, str]]: ...
    def sign_message(self, msg: Message) -> Message: ...
    def sign_message_string(self, message_string: str) -> str: ...
    def sign_message_bytes(self, message_bytes: bytes) -> bytes: ...
