from typing import Any, Optional, Union, List, Dict, Callable, Type
# from premailer import Premailer
# from lxml import etree
from .store import MemoryFileStore, LazyHTTPFile
from .message import Message

class LocalPremailer(Any):
    local_loader: Any
    attribute_name: Optional[str]
    def __init__(self, html: Any, local_loader: Optional[Any] = ..., attribute_name: Optional[str] = ..., **kw: Any) -> None: ...
    def _load_external(self, url: str) -> Optional[str]: ...

class HTMLParser:
    _cdata_regex: Any
    _xml_title_regex: Any
    default_parser_method: str
    default_output_method: str
    _method: str
    _output_method: str
    _html: str
    _tree: Optional[Any]
    def __init__(self, html: str, method: Optional[str] = ..., output_method: Optional[str] = ...) -> None: ...
    @property
    def html(self) -> str: ...
    @property
    def tree(self) -> Any: ...
    def to_string(self, encoding: str = ..., **kwargs: Any) -> str: ...
    def apply_to_images(self, func: Callable[..., Any], images: bool = ..., backgrounds: bool = ..., styles_uri: bool = ...) -> None: ...
    def apply_to_links(self, func: Callable[..., Any]) -> None: ...
    def add_content_type_meta(self, content_type: str = ..., charset: str = ..., element_cls: Type[Any] = ...) -> Optional[Any]: ...
    def save(self, **kwargs: Any) -> None: ...

class BaseTransformer(HTMLParser):
    UNSAFE_TAGS: List[str]
    attachment_store_cls: Type[MemoryFileStore]
    attachment_file_cls: Type[LazyHTTPFile]
    html_attribute_name: str
    attachment_store: MemoryFileStore
    local_loader: Any
    base_url: Optional[str]
    requests_params: Optional[Dict[str, Any]]
    _premailer: Optional[LocalPremailer]
    def __init__(self, html: str, local_loader: Optional[Any] = ..., attachment_store: Optional[MemoryFileStore] = ..., requests_params: Optional[Dict[str, Any]] = ..., method: Optional[str] = ..., base_url: Optional[str] = ...) -> None: ...
    def get_absolute_url(self, url: str) -> str: ...
    def attribute_value(self, el: Any) -> Optional[str]: ...
    _attribute_value: Callable[[Any], Optional[str]]
    def _default_attachment_check(self, el: Any, hints: Dict[str, Any]) -> bool: ...
    def _load_attachment_func(self, uri: str, element: Optional[Any] = ..., callback: Optional[Callable[..., bool]] = ..., **kw: Any) -> str: ...
    def get_premailer(self, **kw: Any) -> LocalPremailer: ...
    @property
    def premailer(self) -> LocalPremailer: ...
    def remove_unsafe_tags(self) -> BaseTransformer: ...
    def load_and_transform(self, css_inline: bool = ..., remove_unsafe_tags: bool = ..., make_links_absolute: bool = ..., set_content_type_meta: bool = ..., update_stylesheet: bool = ..., load_images: Union[bool, Callable[..., bool]] = ..., images_inline: bool = ..., **kw: Any) -> BaseTransformer: ...
    def make_all_images_inline(self) -> BaseTransformer: ...
    def synchronize_inline_images(self, inline_names: Optional[Dict[str, str]] = ..., non_inline_names: Optional[Dict[str, str]] = ...) -> BaseTransformer: ...

class Transformer(BaseTransformer): ...

class MessageTransformer(BaseTransformer):
    message: Message
    def __init__(self, message: Message, **kw: Any) -> None: ...
    def save(self, **kwargs: Any) -> None: ...
