from typing import Any, Optional, List, Union, Dict
from ..message import MessageTransformerMixin, MessageSignMixin, MessageBuildMixin, BaseMessage

class DjangoMessageMixin:
    _recipients: Optional[List[str]]
    _from_email: Optional[str]
    @property
    def encoding(self) -> str: ...
    def recipients(self) -> List[str]: ...
    @property
    def from_email(self) -> str: ...
    def _set_emails(self, mail_to: Optional[Union[str, List[str]]] = ..., set_mail_to: bool = ..., mail_from: Optional[str] = ..., set_mail_from: bool = ..., to: Optional[Union[str, List[str]]] = ...) -> None: ...
    def send(self, mail_to: Optional[Union[str, List[str]]] = ..., set_mail_to: bool = ..., mail_from: Optional[str] = ..., set_mail_from: bool = ..., context: Optional[Dict[str, Any]] = ..., connection: Optional[Any] = ..., to: Optional[Union[str, List[str]]] = ...) -> Any: ...

class DjangoMessage(DjangoMessageMixin, MessageTransformerMixin, MessageSignMixin, MessageBuildMixin, BaseMessage): ...

Message = DjangoMessage
