from typing import Any, Optional, Dict, Union, List, Tuple
from email.mime.base import MIMEBase

MIMETYPE_UNKNOWN: str

def fix_content_type(content_type: Optional[str], t: str = ...) -> str: ...

class BaseFile:
    uri: Optional[str]
    absolute_url: Optional[str]
    filename: Optional[str]
    data: Any
    _mime_type: Optional[str]
    _headers: Dict[str, Any]
    _content_id: Optional[str]
    _content_disposition: str
    subtype: Optional[str]
    local_loader: Any
    _data: Any
    _uri: Optional[str]
    _filename: Optional[str]

    def __init__(self, **kwargs: Any) -> None: ...
    def as_dict(self, fields: Optional[Union[List[str], Tuple[str, ...]]] = ...) -> Dict[str, Any]: ...
    def get_data(self) -> Any: ...
    def set_data(self, value: Any) -> None: ...
    def get_uri(self) -> Optional[str]: ...
    def set_uri(self, value: Optional[str]) -> None: ...
    def get_filename(self) -> Optional[str]: ...
    def set_filename(self, value: Optional[str]) -> None: ...
    def get_mime_type(self) -> str: ...
    @property
    def mime_type(self) -> str: ...
    @property
    def content_disposition(self) -> str: ...
    @property
    def content_id(self) -> Optional[str]: ...
    @property
    def mime(self) -> Optional[MIMEBase]: ...
    @property
    def is_inline(self) -> bool: ...

class LazyHTTPFile(BaseFile):
    requests_args: Optional[Dict[str, Any]]
    _fetched: bool
    def __init__(self, requests_args: Optional[Dict[str, Any]] = ..., **kwargs: Any) -> None: ...
    def fetch(self) -> None: ...
    @property
    def headers(self) -> Dict[str, Any]: ...
