from typing import Any, Optional, Dict, Union, List, Iterator, Type
from .file import BaseFile

class FileStore: ...

class MemoryFileStore(FileStore):
    file_cls: Type[BaseFile]
    _files: Dict[str, BaseFile]
    _filenames: Dict[str, str]

    def __init__(self, file_cls: Optional[Type[BaseFile]] = ...) -> None: ...
    def __contains__(self, k: Any) -> bool: ...
    def keys(self) -> List[str]: ...
    def __len__(self) -> int: ...
    def as_dict(self) -> Iterator[Dict[str, Any]]: ...
    def remove(self, uri: Union[str, BaseFile]) -> None: ...
    def unique_filename(self, filename: str, uri: Optional[str] = ...) -> str: ...
    def add(self, value: Union[BaseFile, Dict[str, Any]], replace: bool = ...) -> BaseFile: ...
    def by_uri(self, uri: str) -> Optional[BaseFile]: ...
    def by_filename(self, filename: str) -> Optional[BaseFile]: ...
    def __getitem__(self, uri: str) -> Optional[BaseFile]: ...
    def __iter__(self) -> Iterator[BaseFile]: ...
